---
  language: go
  notifications:
    email: false
  go:
    - 1.5
  install:
    - go get -t ./...
    - go get github.com/golang/lint/golint
  script:
    - go vet ./...
    - test -z "$(golint ./... | tee /dev/stderr)"
    - test -z "$(gofmt -s -l . | tee /dev/stderr)"
    - go test -v ./...
